CREATE TABLE `applicants` (
	`id` text PRIMARY KEY NOT NULL,
	`surname` text NOT NULL,
	`first_name` text NOT NULL,
	`middle_name` text,
	`suffix` text,
	`date_of_birth` text,
	`sex` text,
	`religion` text,
	`civil_status` text,
	`height` text,
	`contact_number` text,
	`email` text,
	`disability` text,
	`address` text,
	`barangay` text,
	`municipality` text,
	`province` text,
	`employment_status` text,
	`employment_type` text,
	`is_ofw` integer DEFAULT false,
	`is_4ps_beneficiary` integer DEFAULT false,
	`education` text,
	`technical_training` text,
	`language_proficiency` text,
	`work_experience` text,
	`skills` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE `employers` (
	`id` text PRIMARY KEY NOT NULL,
	`establishment_name` text NOT NULL,
	`house_street_village` text,
	`barangay` text,
	`municipality` text,
	`province` text,
	`contact_number` text,
	`email` text,
	`number_of_paid_employees` integer,
	`number_of_vacant_positions` integer,
	`industry_type` text,
	`srs_subscriber` integer DEFAULT false,
	`company_tin` text,
	`business_permit_number` text,
	`bir2303_number` text,
	`chairperson_name` text,
	`chairperson_contact` text,
	`secretary_name` text,
	`secretary_contact` text,
	`prepared_by_name` text,
	`prepared_by_designation` text,
	`prepared_by_contact` text,
	`date_accomplished` text,
	`remarks` text,
	`is_manpower_agency` integer DEFAULT false,
	`dole_certification_number` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE `job_vacancies` (
	`id` text PRIMARY KEY NOT NULL,
	`employer_id` text NOT NULL,
	`establishment_name` text NOT NULL,
	`position_title` text NOT NULL,
	`number_of_vacancies` integer,
	`industry_type` text,
	`minimum_education_required` text,
	`main_skill_or_specialization` text,
	`years_of_experience_required` integer,
	`age_preference` text,
	`starting_salary_or_wage` real,
	`salary_type` text,
	`job_status` text,
	`benefits` text,
	`additional_requirements` text,
	`job_description` text,
	`prepared_by_name` text,
	`prepared_by_designation` text,
	`prepared_by_contact` text,
	`date_accomplished` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
