-- Migration: Drop and recreate users table with NSRP + login fields only
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'jobseeker',
  surname TEXT NOT NULL,
  first_name TEXT NOT NULL,
  middle_name TEXT,
  suffix TEXT,
  date_of_birth TEXT,
  sex TEXT,
  religion TEXT,
  civil_status TEXT,
  height TEXT,
  contact_number TEXT,
  email TEXT NOT NULL UNIQUE,
  disability TEXT,
  disability_specify TEXT,
  address TEXT,
  barangay TEXT,
  municipality TEXT,
  province TEXT,
  employment_status TEXT,
  employment_type TEXT,
  months_unemployed INTEGER,
  is_ofw INTEGER DEFAULT 0,
  owf_country TEXT,
  is_former_ofw INTEGER DEFAULT 0,
  former_ofw_country TEXT,
  return_to_ph_date TEXT,
  is_4ps_beneficiary INTEGER DEFAULT 0,
  household_id TEXT,
  preferred_occupations TEXT,
  preferred_locations TEXT,
  preferred_overseas_countries TEXT,
  employment_type_4 TEXT,
  education TEXT,
  technical_training TEXT,
  professional_licenses TEXT,
  language_proficiency TEXT,
  work_experience TEXT,
  skills TEXT,
  other_skills_specify TEXT,
  created_at INTEGER DEFAULT (strftime('%s','now')) NOT NULL,
  updated_at INTEGER DEFAULT (strftime('%s','now')) NOT NULL
);