import { initializeDatabase } from "../server/database";
import { employersTable, jobsTable } from "../server/unified-schema";
import { hashPassword } from "../server/auth";
import { inArray } from "drizzle-orm";

const DEFAULT_PASSWORD = "Employers@2025";

const barangayDirectory = {
  "Dadiangas North": { code: "126303005", zip: "9500" },
  "Dadiangas South": { code: "126303006", zip: "9500" },
  "Dadiangas East": { code: "126303004", zip: "9500" },
  "Dadiangas West": { code: "126303003", zip: "9500" },
  Lagao: { code: "126303011", zip: "9500" },
  Labangal: { code: "126303008", zip: "9500" },
  Calumpang: { code: "126303002", zip: "9500" },
  Tambler: { code: "126303013", zip: "9500" },
  Apopong: { code: "126303001", zip: "9500" },
  "City Heights": { code: "126303009", zip: "9500" },
  Mabuhay: { code: "126303010", zip: "9500" },
  "San Isidro": { code: "126303012", zip: "9500" },
  Fatima: { code: "126303014", zip: "9500" },
} as const;

type EmployerSeed = {
  id: string;
  establishmentName: string;
  tradeName: string;
  companyType: string;
  industryType: string;
  industryCode: { code: string; description: string };
  street: string;
  barangay: keyof typeof barangayDirectory;
  latitude: number;
  longitude: number;
  contactPerson: string;
  contactDesignation: string;
  contactEmail: string;
  contactNumber: string;
  employees: number;
  vacancies: number;
  remarks: string;
  isManpowerAgency?: boolean;
  chairpersonName: string;
  secretaryName: string;
  barangayChairperson: string;
  barangaySecretary: string;
};

type JobSeed = {
  id: string;
  employerId: string;
  positionTitle: string;
  description: string;
  barangay: keyof typeof barangayDirectory;
  municipality: string;
  province: string;
  salaryMin: number;
  salaryMax: number;
  salaryPeriod: "monthly" | "weekly" | "daily" | "15days";
  salaryType: string;
  specialization: string;
  education: string;
  yearsExperience: number;
  agePreference: string;
  skills: string[];
  requirements: string[];
  vacantPositions: number;
  paidEmployees?: number;
  location: string;
  contactName: string;
  contactNumber: string;
  contactEmail: string;
  preparedByDesignation: string;
  jobStatus: "active" | "pending" | "draft";
  postedAt: string;
  updatedAt: string;
};

const employerSeeds: EmployerSeed[] = [
  {
    id: "gensan_employer_01",
    establishmentName: "General Tuna Corporation",
    tradeName: "GenTuna",
    companyType: "Corporation",
    industryType: "Food Manufacturing",
    industryCode: { code: "C1011", description: "Processing and preserving of fish" },
    street: "RCF Corporate Center, J.P. Laurel Avenue",
    barangay: "Dadiangas North",
    latitude: 6.1221,
    longitude: 125.1754,
    contactPerson: "Maria Teresa Velasco",
    contactDesignation: "HR Director",
    contactEmail: "hr@generaltuna.com",
    contactNumber: "+63 83 552 8801",
    employees: 1200,
    vacancies: 18,
    remarks: "Exports canned tuna to EU and US markets",
    isManpowerAgency: false,
    chairpersonName: "Raul T. Joseph",
    secretaryName: "Loren Mae Dela Cruz",
    barangayChairperson: "Hon. Rizza Tabanao",
    barangaySecretary: "Mary Joy Arcena",
  },
  {
    id: "gensan_employer_02",
    establishmentName: "Philbest Canning Corporation",
    tradeName: "Philbest",
    companyType: "Corporation",
    industryType: "Food Manufacturing",
    industryCode: { code: "C1012", description: "Seafood canning" },
    street: "Makar Wharf Road",
    barangay: "Tambler",
    latitude: 6.0823,
    longitude: 125.1539,
    contactPerson: "Jerome Caballero",
    contactDesignation: "People and Culture Manager",
    contactEmail: "talent@philbest.com",
    contactNumber: "+63 83 552 7888",
    employees: 1400,
    vacancies: 20,
    remarks: "Operates one of the largest tuna canneries in Mindanao",
    chairpersonName: "Ramon C. Santos",
    secretaryName: "Ellaine Rivera",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_03",
    establishmentName: "RD Fishing & Industries, Inc.",
    tradeName: "RD Fishing",
    companyType: "Corporation",
    industryType: "Deep Sea Fishing",
    industryCode: { code: "A0311", description: "Marine fishing" },
    street: "Kingford Complex, Makar Wharf",
    barangay: "Tambler",
    latitude: 6.0788,
    longitude: 125.151,
    contactPerson: "Joelson C. Escobillo",
    contactDesignation: "Fleet HR Head",
    contactEmail: "careers@rdfishing.com",
    contactNumber: "+63 83 553 9900",
    employees: 950,
    vacancies: 25,
    remarks: "Operates purse seine fleets serving the Western Pacific",
    chairpersonName: "Ricardo D. Rivera",
    secretaryName: "Ina Mae Enriquez",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_04",
    establishmentName: "Sarangani Bay Prime Bangus",
    tradeName: "Sarangani Bay",
    companyType: "Corporation",
    industryType: "Seafood Processing",
    industryCode: { code: "C1020", description: "Processing of fish, crustaceans and mollusks" },
    street: "Purok Bayanihan, National Highway",
    barangay: "Calumpang",
    latitude: 6.0944,
    longitude: 125.1955,
    contactPerson: "Angela L. Sinco",
    contactDesignation: "HR Business Partner",
    contactEmail: "talent@sarangani-bay.com",
    contactNumber: "+63 83 552 6671",
    employees: 680,
    vacancies: 12,
    remarks: "Produces value-added bangus products for export",
    chairpersonName: "Norberto S. Daquil",
    secretaryName: "Faye Ann Galenzoga",
    barangayChairperson: "Hon. Rowena Najera",
    barangaySecretary: "Maricel T. Ramos",
  },
  {
    id: "gensan_employer_05",
    establishmentName: "Mega Fishing Corporation",
    tradeName: "Mega Fishing",
    companyType: "Corporation",
    industryType: "Fishing and Logistics",
    industryCode: { code: "A0312", description: "Support services to fishing" },
    street: "Sarangani Drive, Makar",
    barangay: "Tambler",
    latitude: 6.0755,
    longitude: 125.1498,
    contactPerson: "Patrick L. del Mundo",
    contactDesignation: "Crewing and HR Lead",
    contactEmail: "hr@megafishing.ph",
    contactNumber: "+63 83 552 7010",
    employees: 720,
    vacancies: 16,
    remarks: "Handles integrated fishing fleets and shipyard",
    chairpersonName: "Isidro V. Tsai",
    secretaryName: "Noreen P. Cagang",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_06",
    establishmentName: "Ocean Canning Corporation",
    tradeName: "Ocean Canning",
    companyType: "Corporation",
    industryType: "Seafood Export",
    industryCode: { code: "C1021", description: "Canning of fish" },
    street: "Citra Mina Compound, Makar",
    barangay: "Tambler",
    latitude: 6.0772,
    longitude: 125.1529,
    contactPerson: "Janelle Q. Sugano",
    contactDesignation: "People Operations Manager",
    contactEmail: "people@oceancanning.com.ph",
    contactNumber: "+63 83 552 7770",
    employees: 810,
    vacancies: 14,
    remarks: "Operates cold storage and export documentation hub",
    chairpersonName: "Emmanuel N. Samson",
    secretaryName: "Kristine Joy Duque",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_07",
    establishmentName: "KCC Property Holdings, Inc.",
    tradeName: "KCC Mall of Gensan",
    companyType: "Corporation",
    industryType: "Retail and Shopping Centers",
    industryCode: { code: "G4719", description: "Other retail sale in non-specialized stores" },
    street: "Jose Catolico Sr. Avenue",
    barangay: "Lagao",
    latitude: 6.1238,
    longitude: 125.1809,
    contactPerson: "Louella Mae G. Arcena",
    contactDesignation: "Talent Acquisition Head",
    contactEmail: "careers@kccmalls.com",
    contactNumber: "+63 83 301 2345",
    employees: 1500,
    vacancies: 30,
    remarks: "Operates flagship lifestyle mall complex",
    chairpersonName: "Arnel L. Garces",
    secretaryName: "Sheila Ann L. Betita",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_08",
    establishmentName: "SM Prime Holdings, Inc. - SM City General Santos",
    tradeName: "SM City Gensan",
    companyType: "Corporation",
    industryType: "Retail and Property",
    industryCode: { code: "L6810", description: "Real estate activities" },
    street: "Santiago Boulevard corner San Miguel Street",
    barangay: "Lagao",
    latitude: 6.1186,
    longitude: 125.1817,
    contactPerson: "Kristoffer Lee Mitra",
    contactDesignation: "Mall HR Manager",
    contactEmail: "gensan.hr@smprime.com",
    contactNumber: "+63 83 878 0660",
    employees: 1100,
    vacancies: 22,
    remarks: "Premier regional mall complex",
    chairpersonName: "Hans T. Sy",
    secretaryName: "Jennyfer O. Chua",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_09",
    establishmentName: "Robinsons Land Corporation - Robinsons Place General Santos",
    tradeName: "Robinsons Place Gensan",
    companyType: "Corporation",
    industryType: "Retail and Property",
    industryCode: { code: "L6820", description: "Real estate leasing" },
    street: "Jose Catolico Sr. Avenue",
    barangay: "Lagao",
    latitude: 6.1261,
    longitude: 125.179,
    contactPerson: "Daryl R. Pascua",
    contactDesignation: "Mall Administration Manager",
    contactEmail: "hr_gensan@robinsonsland.com",
    contactNumber: "+63 83 554 1230",
    employees: 620,
    vacancies: 10,
    remarks: "Lifestyle mall with GO Hotels and transport terminal",
    chairpersonName: "Frederick D. Go",
    secretaryName: "Maricris G. Alvarez",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_10",
    establishmentName: "Gaisano Grand Mall of General Santos",
    tradeName: "Gaisano Grand",
    companyType: "Corporation",
    industryType: "Retail Trade",
    industryCode: { code: "G4711", description: "Retail sale in department stores" },
    street: "Jose Catolico Sr. Avenue corner Pioneer Avenue",
    barangay: "Dadiangas West",
    latitude: 6.1201,
    longitude: 125.1684,
    contactPerson: "Arvin B. Sumugat",
    contactDesignation: "Complex HR Officer",
    contactEmail: "peopleops@gaisanogensan.com",
    contactNumber: "+63 83 552 2200",
    employees: 500,
    vacancies: 9,
    remarks: "Community mall serving downtown residents",
    chairpersonName: "Stephen T. Gaisano",
    secretaryName: "Lanie U. Llorca",
    barangayChairperson: "Hon. Graham Chiongbian",
    barangaySecretary: "Jemimah S. Abella",
  },
  {
    id: "gensan_employer_11",
    establishmentName: "South Cotabato Integrated Port Services, Inc.",
    tradeName: "SCIPSI",
    companyType: "Corporation",
    industryType: "Port Operations",
    industryCode: { code: "H5224", description: "Cargo handling" },
    street: "Port Users Drive, Makar Wharf",
    barangay: "Tambler",
    latitude: 6.0742,
    longitude: 125.1493,
    contactPerson: "Cecille M. Fetalvero",
    contactDesignation: "Admin & HR Division Chief",
    contactEmail: "hr@scipsi.com",
    contactNumber: "+63 83 552 6600",
    employees: 480,
    vacancies: 11,
    remarks: "Cargo handling concessionaire for Makar Wharf",
    chairpersonName: "Manuel B. Jaravata",
    secretaryName: "Faithlyn B. Gayapa",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_12",
    establishmentName: "Mindanao State University - General Santos",
    tradeName: "MSU Gensan",
    companyType: "Government Educational",
    industryType: "Higher Education",
    industryCode: { code: "P8542", description: "Higher education instruction" },
    street: "Fatima Campus, Tambler-Fatima Road",
    barangay: "Fatima",
    latitude: 6.1081,
    longitude: 125.2059,
    contactPerson: "Prof. Jeffrey P. Omandam",
    contactDesignation: "Director for Administration",
    contactEmail: "hrdo@msugensan.edu.ph",
    contactNumber: "+63 83 554 8600",
    employees: 520,
    vacancies: 13,
    remarks: "State university offering engineering and fisheries",
    chairpersonName: "Dr. Fatima P. Abubakar",
    secretaryName: "Prof. Liezel C. Galo",
    barangayChairperson: "Hon. Rowena Najera",
    barangaySecretary: "Maricel T. Ramos",
  },
  {
    id: "gensan_employer_13",
    establishmentName: "Notre Dame of Dadiangas University",
    tradeName: "NDDU",
    companyType: "Educational Institution",
    industryType: "Higher Education",
    industryCode: { code: "P8522", description: "Private tertiary education" },
    street: "Marist Avenue",
    barangay: "Dadiangas North",
    latitude: 6.1232,
    longitude: 125.1742,
    contactPerson: "Dr. Marilou M. Abrea",
    contactDesignation: "HRMDO Director",
    contactEmail: "hr@nddu.edu.ph",
    contactNumber: "+63 83 552 4444",
    employees: 430,
    vacancies: 8,
    remarks: "Catholic university under the Marist Brothers",
    chairpersonName: "Bro. Roberto C. Ramirez",
    secretaryName: "Ma. Irene A. Dizon",
    barangayChairperson: "Hon. Rizza Tabanao",
    barangaySecretary: "Mary Joy Arcena",
  },
  {
    id: "gensan_employer_14",
    establishmentName: "General Santos Doctors Hospital, Inc.",
    tradeName: "GenSan Doctors Hospital",
    companyType: "Hospital",
    industryType: "Healthcare",
    industryCode: { code: "Q8611", description: "Hospital activities" },
    street: "J. Catolico Sr. Avenue",
    barangay: "Lagao",
    latitude: 6.1194,
    longitude: 125.1807,
    contactPerson: "Dr. Melrose C. Caliguid",
    contactDesignation: "Medical HR Director",
    contactEmail: "hr@gsdh.ph",
    contactNumber: "+63 83 552 5555",
    employees: 750,
    vacancies: 15,
    remarks: "Tertiary hospital serving SOCSKSARGEN",
    chairpersonName: "Dr. Edgar Santos",
    secretaryName: "Dr. Janine Abalos",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_15",
    establishmentName: "St. Elizabeth Hospital of General Santos, Inc.",
    tradeName: "St. Elizabeth Hospital",
    companyType: "Hospital",
    industryType: "Healthcare",
    industryCode: { code: "Q8612", description: "Private hospital activities" },
    street: "National Highway corner J. Catolico Sr. Ave",
    barangay: "Lagao",
    latitude: 6.1181,
    longitude: 125.1819,
    contactPerson: "Nerissa P. Daileg",
    contactDesignation: "HR & Training Manager",
    contactEmail: "talent@stelizabethhospital.com",
    contactNumber: "+63 83 301 7000",
    employees: 520,
    vacancies: 14,
    remarks: "Flagship medical center with ISO-certified labs",
    chairpersonName: "Dr. Rosalie C. Fuentes",
    secretaryName: "Dr. Haydee L. Buenaventura",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_16",
    establishmentName: "Soccsksargen General Hospital",
    tradeName: "SOCSARGEN General",
    companyType: "Hospital",
    industryType: "Healthcare",
    industryCode: { code: "Q8613", description: "Specialty hospital services" },
    street: "National Highway",
    barangay: "San Isidro",
    latitude: 6.142,
    longitude: 125.1628,
    contactPerson: "Dr. Leila Antonette Manalo",
    contactDesignation: "Chief Administrative Officer",
    contactEmail: "hr@socgenhospital.ph",
    contactNumber: "+63 83 553 6000",
    employees: 410,
    vacancies: 9,
    remarks: "Offers specialty cardiac and renal units",
    chairpersonName: "Dr. llyod P. Villanueva",
    secretaryName: "Dr. Daren M. Munda",
    barangayChairperson: "Hon. Dionesio Mondejar",
    barangaySecretary: "Nerissa Joy B. Flores",
  },
  {
    id: "gensan_employer_17",
    establishmentName: "Greenleaf Hotel Gensan",
    tradeName: "Greenleaf Hotel",
    companyType: "Hospitality",
    industryType: "Hotel and Accommodation",
    industryCode: { code: "I5510", description: "Hotels and similar accommodation" },
    street: "San Miguel Street corner J. Catolico Sr. Ave",
    barangay: "Lagao",
    latitude: 6.1184,
    longitude: 125.1812,
    contactPerson: "Roxanne Uy Catalan",
    contactDesignation: "HR Head",
    contactEmail: "hr@greenleafhotelgensan.com",
    contactNumber: "+63 83 553 1111",
    employees: 260,
    vacancies: 6,
    remarks: "Business hotel serving MICE market",
    chairpersonName: "Richard L. Lim",
    secretaryName: "Shiela P. Salazar",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_18",
    establishmentName: "Microtel by Wyndham General Santos",
    tradeName: "Microtel Gensan",
    companyType: "Hospitality",
    industryType: "Hotel and Accommodation",
    industryCode: { code: "I5511", description: "Resort and business hotels" },
    street: "Valley High Complex, National Highway",
    barangay: "Lagao",
    latitude: 6.1236,
    longitude: 125.1825,
    contactPerson: "Jayson Q. Ventura",
    contactDesignation: "People and Culture Lead",
    contactEmail: "hr@microtelgensan.com",
    contactNumber: "+63 83 553 0000",
    employees: 190,
    vacancies: 5,
    remarks: "Midscale hotel serving corporate guests",
    chairpersonName: "Jose Mari del Rosario",
    secretaryName: "Krizia Joy Baldonado",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_19",
    establishmentName: "East Asia Royale Hotel",
    tradeName: "East Asia Royale",
    companyType: "Hospitality",
    industryType: "Hotel and F&B",
    industryCode: { code: "I5610", description: "Food and beverage service activities" },
    street: "National Highway",
    barangay: "Lagao",
    latitude: 6.1231,
    longitude: 125.1835,
    contactPerson: "Lilibeth E. Semillano",
    contactDesignation: "HR Administrator",
    contactEmail: "talent@eastasiaroyalehotel.com",
    contactNumber: "+63 83 553 5555",
    employees: 210,
    vacancies: 4,
    remarks: "Convention hotel hosting large banquets",
    chairpersonName: "William T. Tan",
    secretaryName: "Rosemarie U. Tiam",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_20",
    establishmentName: "RD Pawnshop, Inc.",
    tradeName: "RD Pawnshop",
    companyType: "Corporation",
    industryType: "Financial Services",
    industryCode: { code: "K6492", description: "Other credit granting" },
    street: "Pendleton Building, Pioneer Avenue",
    barangay: "Dadiangas East",
    latitude: 6.1209,
    longitude: 125.1759,
    contactPerson: "Carmela D. Vidanes",
    contactDesignation: "Compliance and HR Director",
    contactEmail: "people@rdpawnshop.com",
    contactNumber: "+63 83 552 9000",
    employees: 880,
    vacancies: 17,
    remarks: "Operates nationwide pawnshop network",
    chairpersonName: "Gerardo L. Rivera",
    secretaryName: "Lennie P. Bolivar",
    barangayChairperson: "Hon. Mila S. Atencio",
    barangaySecretary: "Anthony P. Jumuad",
  },
  {
    id: "gensan_employer_21",
    establishmentName: "RD City Commercial Corporation",
    tradeName: "RD City Commercial",
    companyType: "Corporation",
    industryType: "Real Estate and Facilities",
    industryCode: { code: "L6821", description: "Real estate leasing" },
    street: "RD Plaza, Pendatun Avenue",
    barangay: "Dadiangas West",
    latitude: 6.1188,
    longitude: 125.1712,
    contactPerson: "Antonio P. Magbanua",
    contactDesignation: "Facilities Director",
    contactEmail: "recruitment@rdccc.ph",
    contactNumber: "+63 83 552 4400",
    employees: 360,
    vacancies: 7,
    remarks: "Manages RD Plaza commercial complex",
    chairpersonName: "Rodney T. Del Fierro",
    secretaryName: "Aileen Joy dela Peña",
    barangayChairperson: "Hon. Graham Chiongbian",
    barangaySecretary: "Jemimah S. Abella",
  },
  {
    id: "gensan_employer_22",
    establishmentName: "Sarangani Energy Corporation - GenSan Office",
    tradeName: "Sarangani Energy",
    companyType: "Corporation",
    industryType: "Power Generation",
    industryCode: { code: "D3510", description: "Electric power generation" },
    street: "National Highway",
    barangay: "Calumpang",
    latitude: 6.0955,
    longitude: 125.197,
    contactPerson: "Engr. Aldrin B. Gacula",
    contactDesignation: "People Department Head",
    contactEmail: "talent@sarangani-energy.com",
    contactNumber: "+63 83 305 5000",
    employees: 430,
    vacancies: 9,
    remarks: "Operates base-load coal plant serving Mindanao",
    chairpersonName: "Teresita T. Sy-Coson",
    secretaryName: "Geneva Mae L. Borja",
    barangayChairperson: "Hon. Rowena Najera",
    barangaySecretary: "Maricel T. Ramos",
  },
  {
    id: "gensan_employer_23",
    establishmentName: "Coca-Cola Beverages Philippines, Inc. - General Santos",
    tradeName: "Coke Beverages PH",
    companyType: "Corporation",
    industryType: "Beverage Manufacturing",
    industryCode: { code: "C1107", description: "Manufacture of soft drinks" },
    street: "Purok 7, National Highway",
    barangay: "Calumpang",
    latitude: 6.0915,
    longitude: 125.1988,
    contactPerson: "Chester N. Eramis",
    contactDesignation: "Plant HR Manager",
    contactEmail: "gensan.hr@coke.com.ph",
    contactNumber: "+63 83 553 1888",
    employees: 520,
    vacancies: 12,
    remarks: "Operates bottling and distribution plant",
    chairpersonName: "Antonio del Rosario",
    secretaryName: "Michelle C. Abalos",
    barangayChairperson: "Hon. Rowena Najera",
    barangaySecretary: "Maricel T. Ramos",
  },
  {
    id: "gensan_employer_24",
    establishmentName: "Holcim Philippines, Inc. - Makar Plant",
    tradeName: "Holcim Makar",
    companyType: "Corporation",
    industryType: "Cement Manufacturing",
    industryCode: { code: "C2394", description: "Manufacture of cement" },
    street: "Makar Industrial Road",
    barangay: "Labangal",
    latitude: 6.0895,
    longitude: 125.1715,
    contactPerson: "Engr. Reynaldo T. Versoza",
    contactDesignation: "People Performance Lead",
    contactEmail: "careers@holcim.com.ph",
    contactNumber: "+63 83 553 4300",
    employees: 380,
    vacancies: 8,
    remarks: "Grinding facility supplying SOCCSKSARGEN",
    chairpersonName: "Horia Adrian",
    secretaryName: "Carla S. Agraviador",
    barangayChairperson: "Hon. Henry Noble",
    barangaySecretary: "Kristine Joy Mahusay",
  },
  {
    id: "gensan_employer_25",
    establishmentName: "Phoenix Petroleum Philippines - General Santos Depot",
    tradeName: "Phoenix Petroleum",
    companyType: "Corporation",
    industryType: "Fuel Storage and Distribution",
    industryCode: { code: "G4680", description: "Wholesale of fuel" },
    street: "Tambler Industrial Complex",
    barangay: "Tambler",
    latitude: 6.0711,
    longitude: 125.1484,
    contactPerson: "Carlo Bryce Uy",
    contactDesignation: "Terminal HR Supervisor",
    contactEmail: "terminal.hr@phoenixfuels.ph",
    contactNumber: "+63 83 552 7700",
    employees: 210,
    vacancies: 6,
    remarks: "Handles bulk fuel depot for SOX",
    chairpersonName: "Dennis A. Uy",
    secretaryName: "Cherry Ann B. del Rosario",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_26",
    establishmentName: "Pilipinas Shell Petroleum Corporation - General Santos Terminal",
    tradeName: "Shell GenSan Terminal",
    companyType: "Corporation",
    industryType: "Fuel Storage and Distribution",
    industryCode: { code: "G4681", description: "Wholesale of petroleum" },
    street: "Makar Wharf Access Road",
    barangay: "Tambler",
    latitude: 6.0702,
    longitude: 125.1492,
    contactPerson: "Engr. Lianne Rose Cueno",
    contactDesignation: "Terminal HSSE Manager",
    contactEmail: "gensan.hr@shell.com",
    contactNumber: "+63 83 552 8800",
    employees: 190,
    vacancies: 5,
    remarks: "Stores finished fuels for South Mindanao",
    chairpersonName: "Lorelie Q. Osial",
    secretaryName: "Maria Juliana Jara",
    barangayChairperson: "Hon. Jose Luis Rivera",
    barangaySecretary: "Jeanette C. Lagaac",
  },
  {
    id: "gensan_employer_27",
    establishmentName: "PLDT Enterprise - General Santos Hub",
    tradeName: "PLDT Enterprise",
    companyType: "Corporation",
    industryType: "Telecommunications",
    industryCode: { code: "J6110", description: "Wired telecommunications" },
    street: "Osmeña South Street",
    barangay: "Dadiangas South",
    latitude: 6.1156,
    longitude: 125.1752,
    contactPerson: "Michael Angelo Tabora",
    contactDesignation: "Area HR Business Partner",
    contactEmail: "mindanao.hr@pldt.com.ph",
    contactNumber: "+63 83 301 7600",
    employees: 260,
    vacancies: 7,
    remarks: "Regional enterprise sales hub",
    chairpersonName: "Alfredo S. Panlilio",
    secretaryName: "Shiela P. Pecson",
    barangayChairperson: "Hon. Avelino Itaas",
    barangaySecretary: "Isabel Carandang",
  },
  {
    id: "gensan_employer_28",
    establishmentName: "Globe Telecom, Inc. - General Santos Regional Office",
    tradeName: "Globe Telecom",
    companyType: "Corporation",
    industryType: "Telecommunications",
    industryCode: { code: "J6120", description: "Wireless telecommunications" },
    street: "J. Catolico Sr. Avenue",
    barangay: "Dadiangas East",
    latitude: 6.1197,
    longitude: 125.1769,
    contactPerson: "Jamie Rose Mangao",
    contactDesignation: "People Experience Lead",
    contactEmail: "peoplexp@globe.com.ph",
    contactNumber: "+63 83 552 8808",
    employees: 230,
    vacancies: 6,
    remarks: "Manages network operations for SOCSKSARGEN",
    chairpersonName: "Ernest L. Cu",
    secretaryName: "Yvette Jane Hafinia",
    barangayChairperson: "Hon. Mila S. Atencio",
    barangaySecretary: "Anthony P. Jumuad",
  },
  {
    id: "gensan_employer_29",
    establishmentName: "Concentrix CVG Philippines, Inc. - General Santos",
    tradeName: "Concentrix Gensan",
    companyType: "BPO",
    industryType: "Business Process Outsourcing",
    industryCode: { code: "N8220", description: "Call center activities" },
    street: "SPC Compound, National Highway",
    barangay: "Lagao",
    latitude: 6.1294,
    longitude: 125.1827,
    contactPerson: "Bryan Carlo Catamco",
    contactDesignation: "Site Director",
    contactEmail: "gensan.recruitment@concentrix.com",
    contactNumber: "+63 83 305 6000",
    employees: 1800,
    vacancies: 60,
    remarks: "Voice and non-voice operations serving US clients",
    chairpersonName: "Chris Caldwell",
    secretaryName: "Grace Lynne Sevilla",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_30",
    establishmentName: "Sutherland Global Services Philippines, Inc. - General Santos",
    tradeName: "Sutherland Gensan",
    companyType: "BPO",
    industryType: "Business Process Outsourcing",
    industryCode: { code: "N8211", description: "Customer relationship management" },
    street: "SM City General Santos IT Tower",
    barangay: "Lagao",
    latitude: 6.1182,
    longitude: 125.1813,
    contactPerson: "Katrina Mae Inigo",
    contactDesignation: "Talent Acquisition Senior Manager",
    contactEmail: "talent@sutherlandglobal.com",
    contactNumber: "+63 83 305 6200",
    employees: 1600,
    vacancies: 55,
    remarks: "Financial services and healthcare accounts",
    chairpersonName: "Lorenzo T. Navarrete",
    secretaryName: "Janella B. Bohol",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_31",
    establishmentName: "General Santos City Water District",
    tradeName: "GSCWD",
    companyType: "Government Owned",
    industryType: "Utilities",
    industryCode: { code: "E3600", description: "Water collection, treatment and supply" },
    street: "J. Catolico Sr. Avenue",
    barangay: "Lagao",
    latitude: 6.1219,
    longitude: 125.1814,
    contactPerson: "Engr. Sophia D. Gamalinda",
    contactDesignation: "Administrative Services Manager",
    contactEmail: "hr@gscwd.gov.ph",
    contactNumber: "+63 83 553 5559",
    employees: 390,
    vacancies: 10,
    remarks: "Operates city-wide water utility",
    chairpersonName: "Engr. Luisa L. Rivera",
    secretaryName: "Lovella R. Ang",
    barangayChairperson: "Hon. Erlinda Generalao",
    barangaySecretary: "Rowena B. Panganiban",
  },
  {
    id: "gensan_employer_32",
    establishmentName: "Pryce Gases, Inc. - General Santos Filling Plant",
    tradeName: "Pryce Gases",
    companyType: "Corporation",
    industryType: "Industrial Gas",
    industryCode: { code: "C2011", description: "Manufacture of industrial gases" },
    street: "Fatima-Mag. Road",
    barangay: "Fatima",
    latitude: 6.1108,
    longitude: 125.2064,
    contactPerson: "Engr. Romeo A. Lim",
    contactDesignation: "Plant Operations Head",
    contactEmail: "gensan.plant@prycegas.com",
    contactNumber: "+63 83 553 4555",
    employees: 210,
    vacancies: 5,
    remarks: "Supplies LPG and medical oxygen",
    chairpersonName: "Ignacio T. Prats",
    secretaryName: "Marian G. Yulo",
    barangayChairperson: "Hon. Rowena Najera",
    barangaySecretary: "Maricel T. Ramos",
  },
  {
    id: "gensan_employer_33",
    establishmentName: "TSP Marine Industries, Inc.",
    tradeName: "TSP Marine",
    companyType: "Corporation",
    industryType: "Ship Repair and Fabrication",
    industryCode: { code: "C3012", description: "Building of pleasure and sporting boats" },
    street: "Queen Tuna Park Road",
    barangay: "Dadiangas South",
    latitude: 6.1106,
    longitude: 125.1736,
    contactPerson: "Engr. Denver P. Saavedra",
    contactDesignation: "Shipyard HR Head",
    contactEmail: "hr@tspmarine.com",
    contactNumber: "+63 83 552 3300",
    employees: 260,
    vacancies: 8,
    remarks: "Provides ship repair and fabrication services",
    chairpersonName: "Teodomiro P. Lim",
    secretaryName: "Carina Mae Codilla",
    barangayChairperson: "Hon. Avelino Itaas",
    barangaySecretary: "Isabel Carandang",
  },
];

const jobSeeds: JobSeed[] = [
  {
    id: "gensan_job_001",
    employerId: "gensan_employer_01",
    positionTitle: "Quality Assurance Supervisor",
    description: "Lead HACCP implementation and sensory evaluation for canned tuna lines.",
    barangay: "Dadiangas North",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 32000,
    salaryMax: 42000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Seafood Quality Systems",
    education: "BS Food Technology",
    yearsExperience: 5,
    agePreference: "25-40",
    skills: ["HACCP", "GMP Audits", "Team Leadership"],
    requirements: ["Lead HACCP certification", "5 years QA experience", "Willing to work shifting schedules"],
    vacantPositions: 2,
    paidEmployees: 1200,
    location: "RCF Corporate Center, J.P. Laurel Avenue, General Santos City",
    contactName: "Maria Teresa Velasco",
    contactNumber: "+63 83 552 8801",
    contactEmail: "recruitment@generaltuna.com",
    preparedByDesignation: "HR Director",
    jobStatus: "active",
    postedAt: "2025-11-15T08:00:00+08:00",
    updatedAt: "2025-12-01T10:00:00+08:00",
  },
  {
    id: "gensan_job_002",
    employerId: "gensan_employer_02",
    positionTitle: "Production Planning Specialist",
    description: "Balance raw fish intake, canning schedules, and shipment commitments.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 30000,
    salaryMax: 38000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Manufacturing Planning",
    education: "BS Industrial Engineering",
    yearsExperience: 4,
    agePreference: "24-38",
    skills: ["SAP PP", "Capacity Planning", "Analytics"],
    requirements: ["Experience in FMCG planning", "Can analyze cold storage inventory", "Understands export lead times"],
    vacantPositions: 1,
    paidEmployees: 1400,
    location: "Makar Wharf Road, Tambler, General Santos City",
    contactName: "Jerome Caballero",
    contactNumber: "+63 83 552 7888",
    contactEmail: "talent@philbest.com",
    preparedByDesignation: "People and Culture Manager",
    jobStatus: "active",
    postedAt: "2025-11-12T08:00:00+08:00",
    updatedAt: "2025-11-30T17:00:00+08:00",
  },
  {
    id: "gensan_job_003",
    employerId: "gensan_employer_03",
    positionTitle: "Dock Safety Officer",
    description: "Supervise port safety protocols for purse seine unloading operations.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 28000,
    salaryMax: 36000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Port Safety",
    education: "BS Marine Engineering",
    yearsExperience: 3,
    agePreference: "25-40",
    skills: ["OSH", "Incident Investigation", "Crew Briefing"],
    requirements: ["DOLE accredited Safety Officer 2", "Experience in port or shipyard", "Knowledge of PPE compliance"],
    vacantPositions: 2,
    paidEmployees: 950,
    location: "Kingford Complex, Makar Wharf, General Santos City",
    contactName: "Joelson C. Escobillo",
    contactNumber: "+63 83 553 9900",
    contactEmail: "careers@rdfishing.com",
    preparedByDesignation: "Fleet HR Head",
    jobStatus: "active",
    postedAt: "2025-11-10T07:30:00+08:00",
    updatedAt: "2025-11-28T16:30:00+08:00",
  },
  {
    id: "gensan_job_004",
    employerId: "gensan_employer_04",
    positionTitle: "Cold Storage Technician",
    description: "Maintain ammonia refrigeration systems for deboned bangus operations.",
    barangay: "Calumpang",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 26000,
    salaryMax: 32000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Industrial Refrigeration",
    education: "BS Mechanical Engineering",
    yearsExperience: 3,
    agePreference: "23-38",
    skills: ["Ammonia Systems", "Preventive Maintenance", "Instrumentation"],
    requirements: ["TESDA NC II Refrigeration", "Knowledge in PLC controls", "Ready for shifting schedule"],
    vacantPositions: 3,
    location: "Purok Bayanihan, National Highway, Calumpang, General Santos City",
    contactName: "Angela L. Sinco",
    contactNumber: "+63 83 552 6671",
    contactEmail: "talent@sarangani-bay.com",
    preparedByDesignation: "HR Business Partner",
    jobStatus: "active",
    postedAt: "2025-11-08T09:00:00+08:00",
    updatedAt: "2025-11-27T15:45:00+08:00",
  },
  {
    id: "gensan_job_005",
    employerId: "gensan_employer_05",
    positionTitle: "Fleet Maintenance Engineer",
    description: "Coordinate dry-docking schedule and machinery maintenance for fishing vessels.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 40000,
    salaryMax: 52000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Marine Engineering",
    education: "BS Marine Engineering",
    yearsExperience: 6,
    agePreference: "27-45",
    skills: ["Planned Maintenance", "Class Society Compliance", "People Management"],
    requirements: ["Licensed Marine Engineer", "Shipyard coordination experience", "Knowledge of hydraulic systems"],
    vacantPositions: 1,
    location: "Sarangani Drive, Makar, General Santos City",
    contactName: "Patrick L. del Mundo",
    contactNumber: "+63 83 552 7010",
    contactEmail: "hr@megafishing.ph",
    preparedByDesignation: "Crewing and HR Lead",
    jobStatus: "active",
    postedAt: "2025-11-05T09:15:00+08:00",
    updatedAt: "2025-11-25T11:30:00+08:00",
  },
  {
    id: "gensan_job_006",
    employerId: "gensan_employer_06",
    positionTitle: "Export Documentation Analyst",
    description: "Prepare EU and US export documents, coordinate with customs brokers.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 25000,
    salaryMax: 31000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Export Compliance",
    education: "BS Customs Administration",
    yearsExperience: 2,
    agePreference: "22-32",
    skills: ["PEZA Systems", "FDA Export Rules", "Attention to Detail"],
    requirements: ["Knowledge of e2m Customs", "Good coordination skills", "Can work weekend rotation"],
    vacantPositions: 2,
    location: "Citra Mina Compound, Makar, General Santos City",
    contactName: "Janelle Q. Sugano",
    contactNumber: "+63 83 552 7770",
    contactEmail: "people@oceancanning.com.ph",
    preparedByDesignation: "People Operations Manager",
    jobStatus: "active",
    postedAt: "2025-11-04T08:30:00+08:00",
    updatedAt: "2025-11-24T10:30:00+08:00",
  },
  {
    id: "gensan_job_007",
    employerId: "gensan_employer_07",
    positionTitle: "Mall Leasing Specialist",
    description: "Manage specialty leasing pipeline and negotiate inline store renewals.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 35000,
    salaryMax: 45000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Retail Leasing",
    education: "BS Marketing",
    yearsExperience: 4,
    agePreference: "24-38",
    skills: ["Client Negotiation", "Space Planning", "Sales Forecasting"],
    requirements: ["At least 2 years mall leasing", "Strong presentation skills", "Comfortable with CRM tools"],
    vacantPositions: 2,
    location: "Jose Catolico Sr. Avenue, Lagao, General Santos City",
    contactName: "Louella Mae G. Arcena",
    contactNumber: "+63 83 301 2345",
    contactEmail: "careers@kccmalls.com",
    preparedByDesignation: "Talent Acquisition Head",
    jobStatus: "active",
    postedAt: "2025-11-03T09:00:00+08:00",
    updatedAt: "2025-11-22T17:00:00+08:00",
  },
  {
    id: "gensan_job_008",
    employerId: "gensan_employer_08",
    positionTitle: "Mall Marketing Officer",
    description: "Execute traffic-driving campaigns and digital content for SM City General Santos.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 33000,
    salaryMax: 42000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Mall Marketing",
    education: "BS Communications",
    yearsExperience: 3,
    agePreference: "23-35",
    skills: ["Digital Marketing", "Event Production", "Vendor Management"],
    requirements: ["Handled mall events", "Skilled in social media analytics", "Can work weekends/holidays"],
    vacantPositions: 1,
    location: "Santiago Blvd cor. San Miguel St, Lagao, General Santos City",
    contactName: "Kristoffer Lee Mitra",
    contactNumber: "+63 83 878 0660",
    contactEmail: "gensan.hr@smprime.com",
    preparedByDesignation: "Mall HR Manager",
    jobStatus: "active",
    postedAt: "2025-11-02T10:00:00+08:00",
    updatedAt: "2025-11-21T16:00:00+08:00",
  },
  {
    id: "gensan_job_009",
    employerId: "gensan_employer_09",
    positionTitle: "Tenant Relations Coordinator",
    description: "Ensure operational compliance of mall tenants and support fit-out approvals.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 28000,
    salaryMax: 34000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Property Management",
    education: "BS Business Administration",
    yearsExperience: 2,
    agePreference: "23-33",
    skills: ["Customer Service", "Documentation", "Basic AutoCAD"],
    requirements: ["Tenant coordination experience", "Understands mall house rules", "Can facilitate punch-listing"],
    vacantPositions: 2,
    location: "Jose Catolico Sr. Avenue, Lagao, General Santos City",
    contactName: "Daryl R. Pascua",
    contactNumber: "+63 83 554 1230",
    contactEmail: "hr_gensan@robinsonsland.com",
    preparedByDesignation: "Mall Administration Manager",
    jobStatus: "active",
    postedAt: "2025-11-01T09:30:00+08:00",
    updatedAt: "2025-11-20T15:00:00+08:00",
  },
  {
    id: "gensan_job_010",
    employerId: "gensan_employer_10",
    positionTitle: "Security Shift Supervisor",
    description: "Supervise guard deployments, CCTV analytics, and incident reporting for Gaisano Mall.",
    barangay: "Dadiangas West",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 23000,
    salaryMax: 28000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Security Operations",
    education: "Any 4-year course",
    yearsExperience: 3,
    agePreference: "25-45",
    skills: ["CCTV Monitoring", "Report Writing", "Emergency Response"],
    requirements: ["Holder of SOSIA license", "Leadership in mall security", "Can coordinate with PNP-BFP"],
    vacantPositions: 2,
    location: "Jose Catolico Sr. Ave corner Pioneer Ave, General Santos City",
    contactName: "Arvin B. Sumugat",
    contactNumber: "+63 83 552 2200",
    contactEmail: "peopleops@gaisanogensan.com",
    preparedByDesignation: "Complex HR Officer",
    jobStatus: "active",
    postedAt: "2025-10-30T08:30:00+08:00",
    updatedAt: "2025-11-19T12:00:00+08:00",
  },
  {
    id: "gensan_job_011",
    employerId: "gensan_employer_11",
    positionTitle: "Port Operations Scheduler",
    description: "Sequence docking windows, crane assignments, and reefer plug loads at Makar Wharf.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 36000,
    salaryMax: 46000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Port Logistics",
    education: "BS Maritime Transportation",
    yearsExperience: 4,
    agePreference: "24-40",
    skills: ["Vessel Scheduling", "Yard Management", "Stakeholder Coordination"],
    requirements: ["Experience with terminal operating systems", "Understands cold-chain handling", "Can work rotating shifts"],
    vacantPositions: 1,
    location: "Port Users Drive, Makar Wharf, General Santos City",
    contactName: "Cecille M. Fetalvero",
    contactNumber: "+63 83 552 6600",
    contactEmail: "hr@scipsi.com",
    preparedByDesignation: "Admin & HR Division Chief",
    jobStatus: "active",
    postedAt: "2025-10-29T09:00:00+08:00",
    updatedAt: "2025-11-18T16:30:00+08:00",
  },
  {
    id: "gensan_job_012",
    employerId: "gensan_employer_12",
    positionTitle: "University IT Administrator",
    description: "Manage campus network, LMS uptime, and cybersecurity compliance.",
    barangay: "Fatima",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 29000,
    salaryMax: 36000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "IT Infrastructure",
    education: "BS Information Technology",
    yearsExperience: 3,
    agePreference: "23-38",
    skills: ["Network Administration", "Azure AD", "Linux Servers"],
    requirements: ["Handled campus IT environment", "Knowledge of ISO 27001", "Can manage LMS upgrades"],
    vacantPositions: 2,
    location: "Fatima Campus, General Santos City",
    contactName: "Prof. Jeffrey P. Omandam",
    contactNumber: "+63 83 554 8600",
    contactEmail: "hrdo@msugensan.edu.ph",
    preparedByDesignation: "Director for Administration",
    jobStatus: "active",
    postedAt: "2025-10-27T08:15:00+08:00",
    updatedAt: "2025-11-17T14:00:00+08:00",
  },
  {
    id: "gensan_job_013",
    employerId: "gensan_employer_13",
    positionTitle: "Registrar Data Analyst",
    description: "Streamline enrollment analytics and automate transcript generation workflows.",
    barangay: "Dadiangas North",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 25000,
    salaryMax: 31000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Academic Records",
    education: "BS Information Systems",
    yearsExperience: 2,
    agePreference: "22-35",
    skills: ["SQL", "Power BI", "Registrar Policies"],
    requirements: ["Experience in education data", "Knowledge of CHED compliance", "Strong documentation skills"],
    vacantPositions: 1,
    location: "Marist Avenue, Dadiangas North, General Santos City",
    contactName: "Dr. Marilou M. Abrea",
    contactNumber: "+63 83 552 4444",
    contactEmail: "hr@nddu.edu.ph",
    preparedByDesignation: "HRMDO Director",
    jobStatus: "active",
    postedAt: "2025-10-26T10:00:00+08:00",
    updatedAt: "2025-11-16T13:30:00+08:00",
  },
  {
    id: "gensan_job_014",
    employerId: "gensan_employer_14",
    positionTitle: "Clinical Pharmacist",
    description: "Provide medication therapy management for oncology and critical care units.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 42000,
    salaryMax: 52000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Hospital Pharmacy",
    education: "Licensed Pharmacist",
    yearsExperience: 3,
    agePreference: "25-40",
    skills: ["Medication Review", "Antimicrobial Stewardship", "Patient Counseling"],
    requirements: ["PRC Pharmacist License", "Hospital exposure", "Training on clinical pharmacy"],
    vacantPositions: 2,
    location: "J. Catolico Sr. Avenue, Lagao, General Santos City",
    contactName: "Dr. Melrose C. Caliguid",
    contactNumber: "+63 83 552 5555",
    contactEmail: "hr@gsdh.ph",
    preparedByDesignation: "Medical HR Director",
    jobStatus: "active",
    postedAt: "2025-10-24T09:45:00+08:00",
    updatedAt: "2025-11-14T16:45:00+08:00",
  },
  {
    id: "gensan_job_015",
    employerId: "gensan_employer_15",
    positionTitle: "Nurse Supervisor",
    description: "Supervise medical-surgical unit staffing, audits and patient safety rounds.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 38000,
    salaryMax: 48000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Nursing Leadership",
    education: "BS Nursing",
    yearsExperience: 5,
    agePreference: "27-45",
    skills: ["Clinical Supervision", "Patient Safety", "Coaching"],
    requirements: ["Active PRC RN license", "BLS/ACLS certified", "Ward leadership experience"],
    vacantPositions: 2,
    location: "National Highway corner J. Catolico Sr. Ave, Lagao, General Santos City",
    contactName: "Nerissa P. Daileg",
    contactNumber: "+63 83 301 7000",
    contactEmail: "talent@stelizabethhospital.com",
    preparedByDesignation: "HR & Training Manager",
    jobStatus: "active",
    postedAt: "2025-10-23T08:20:00+08:00",
    updatedAt: "2025-11-13T14:15:00+08:00",
  },
  {
    id: "gensan_job_016",
    employerId: "gensan_employer_16",
    positionTitle: "Biomedical Technician",
    description: "Maintain dialysis, ventilator, and imaging equipment for specialty units.",
    barangay: "San Isidro",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 30000,
    salaryMax: 36000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Biomedical Engineering",
    education: "BS Electronics Engineering",
    yearsExperience: 3,
    agePreference: "23-38",
    skills: ["Medical Equipment Repair", "Calibration", "Vendor Coordination"],
    requirements: ["TESDA Biomedical Equipment certification", "Hospital experience", "Can be on-call"],
    vacantPositions: 1,
    location: "National Highway, San Isidro, General Santos City",
    contactName: "Dr. Leila Antonette Manalo",
    contactNumber: "+63 83 553 6000",
    contactEmail: "hr@socgenhospital.ph",
    preparedByDesignation: "Chief Administrative Officer",
    jobStatus: "active",
    postedAt: "2025-10-22T09:10:00+08:00",
    updatedAt: "2025-11-12T13:40:00+08:00",
  },
  {
    id: "gensan_job_017",
    employerId: "gensan_employer_17",
    positionTitle: "Front Office Manager",
    description: "Oversee guest relations, concierge services, and PMS performance.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 45000,
    salaryMax: 55000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Hotel Operations",
    education: "BS Hospitality Management",
    yearsExperience: 6,
    agePreference: "28-45",
    skills: ["Opera PMS", "Guest Recovery", "Team Coaching"],
    requirements: ["Luxury hotel background", "Handled 24/7 operations", "Excellent communication"],
    vacantPositions: 1,
    location: "San Miguel St corner J. Catolico Sr Ave, Lagao, General Santos City",
    contactName: "Roxanne Uy Catalan",
    contactNumber: "+63 83 553 1111",
    contactEmail: "hr@greenleafhotelgensan.com",
    preparedByDesignation: "HR Head",
    jobStatus: "active",
    postedAt: "2025-10-20T10:30:00+08:00",
    updatedAt: "2025-11-11T16:00:00+08:00",
  },
  {
    id: "gensan_job_018",
    employerId: "gensan_employer_18",
    positionTitle: "Events Sales Executive",
    description: "Drive banquet and corporate bookings for Microtel function rooms.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 26000,
    salaryMax: 32000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Events Sales",
    education: "BS Tourism",
    yearsExperience: 2,
    agePreference: "22-35",
    skills: ["Client Prospecting", "Proposal Writing", "Event Coordination"],
    requirements: ["Hotel sales background", "Owns reliable network", "Can work weekends"],
    vacantPositions: 2,
    location: "Valley High Complex, Lagao, General Santos City",
    contactName: "Jayson Q. Ventura",
    contactNumber: "+63 83 553 0000",
    contactEmail: "hr@microtelgensan.com",
    preparedByDesignation: "People and Culture Lead",
    jobStatus: "active",
    postedAt: "2025-10-19T09:00:00+08:00",
    updatedAt: "2025-11-09T13:00:00+08:00",
  },
  {
    id: "gensan_job_019",
    employerId: "gensan_employer_19",
    positionTitle: "Food & Beverage Supervisor",
    description: "Handle restaurant floor operations and banquet setups at East Asia Royale Hotel.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 24000,
    salaryMax: 30000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "F&B Operations",
    education: "BS HRM",
    yearsExperience: 3,
    agePreference: "23-38",
    skills: ["Service Standards", "Inventory Control", "Staff Training"],
    requirements: ["Hotel F&B experience", "Knowledge of POS", "Can manage large banquets"],
    vacantPositions: 2,
    location: "National Highway, Lagao, General Santos City",
    contactName: "Lilibeth E. Semillano",
    contactNumber: "+63 83 553 5555",
    contactEmail: "talent@eastasiaroyalehotel.com",
    preparedByDesignation: "HR Administrator",
    jobStatus: "active",
    postedAt: "2025-10-18T08:45:00+08:00",
    updatedAt: "2025-11-08T12:00:00+08:00",
  },
  {
    id: "gensan_job_020",
    employerId: "gensan_employer_20",
    positionTitle: "Risk Compliance Officer",
    description: "Conduct pawnshop branch audits and AML monitoring across SOCSKSARGEN.",
    barangay: "Dadiangas East",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 33000,
    salaryMax: 42000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Compliance",
    education: "BS Accountancy",
    yearsExperience: 4,
    agePreference: "24-40",
    skills: ["AML Monitoring", "Internal Audit", "Report Writing"],
    requirements: ["Knowledge of BSP regulations", "Willing to travel", "Can use audit analytics"],
    vacantPositions: 2,
    location: "Pendleton Building, Pioneer Ave, General Santos City",
    contactName: "Carmela D. Vidanes",
    contactNumber: "+63 83 552 9000",
    contactEmail: "people@rdpawnshop.com",
    preparedByDesignation: "Compliance and HR Director",
    jobStatus: "active",
    postedAt: "2025-10-17T09:20:00+08:00",
    updatedAt: "2025-11-07T11:45:00+08:00",
  },
  {
    id: "gensan_job_021",
    employerId: "gensan_employer_21",
    positionTitle: "Facilities Engineer",
    description: "Manage preventive maintenance of RD Plaza chillers, elevators, and gensets.",
    barangay: "Dadiangas West",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 36000,
    salaryMax: 46000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Facilities Management",
    education: "BS Mechanical Engineering",
    yearsExperience: 4,
    agePreference: "25-40",
    skills: ["Facilities Planning", "MEP Systems", "Contractor Management"],
    requirements: ["Licensed ME", "Experience with Building Automation", "Can supervise technicians"],
    vacantPositions: 1,
    location: "RD Plaza, Pendatun Ave, General Santos City",
    contactName: "Antonio P. Magbanua",
    contactNumber: "+63 83 552 4400",
    contactEmail: "recruitment@rdccc.ph",
    preparedByDesignation: "Facilities Director",
    jobStatus: "active",
    postedAt: "2025-10-16T09:35:00+08:00",
    updatedAt: "2025-11-06T15:30:00+08:00",
  },
  {
    id: "gensan_job_022",
    employerId: "gensan_employer_22",
    positionTitle: "Plant Shift Supervisor",
    description: "Coordinate generation dispatch, coal yard operations, and substation interface.",
    barangay: "Calumpang",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 52000,
    salaryMax: 62000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Power Plant Operations",
    education: "BS Electrical Engineering",
    yearsExperience: 6,
    agePreference: "28-45",
    skills: ["Generation Dispatch", "SCADA", "Team Leadership"],
    requirements: ["Experience in coal or thermal plant", "PEE or REE preferred", "Can lead shift teams"],
    vacantPositions: 2,
    location: "National Highway, Calumpang, General Santos City",
    contactName: "Engr. Aldrin B. Gacula",
    contactNumber: "+63 83 305 5000",
    contactEmail: "talent@sarangani-energy.com",
    preparedByDesignation: "People Department Head",
    jobStatus: "active",
    postedAt: "2025-10-15T08:40:00+08:00",
    updatedAt: "2025-11-05T14:30:00+08:00",
  },
  {
    id: "gensan_job_023",
    employerId: "gensan_employer_23",
    positionTitle: "Production Line Electrician",
    description: "Ensure bottling line electrical reliability and respond to downtime events.",
    barangay: "Calumpang",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 28000,
    salaryMax: 34000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Industrial Maintenance",
    education: "BS Electrical Technology",
    yearsExperience: 3,
    agePreference: "22-35",
    skills: ["PLC", "Motor Control", "Troubleshooting"],
    requirements: ["TESDA NC II Electrical", "Experience in FMCG", "Can work in shifts"],
    vacantPositions: 3,
    location: "Purok 7, National Highway, Calumpang, General Santos City",
    contactName: "Chester N. Eramis",
    contactNumber: "+63 83 553 1888",
    contactEmail: "gensan.hr@coke.com.ph",
    preparedByDesignation: "Plant HR Manager",
    jobStatus: "active",
    postedAt: "2025-10-14T08:10:00+08:00",
    updatedAt: "2025-11-04T11:50:00+08:00",
  },
  {
    id: "gensan_job_024",
    employerId: "gensan_employer_24",
    positionTitle: "Process Control Specialist",
    description: "Monitor cement grinding parameters, quality sampling, and SCADA alarms.",
    barangay: "Labangal",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 42000,
    salaryMax: 52000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Process Engineering",
    education: "BS Chemical Engineering",
    yearsExperience: 5,
    agePreference: "26-45",
    skills: ["SCADA", "Process Optimization", "QC Analysis"],
    requirements: ["Experience in cement or similar", "Knowledge of ISO 9001", "Willing to be on shifting"],
    vacantPositions: 1,
    location: "Makar Industrial Road, Labangal, General Santos City",
    contactName: "Engr. Reynaldo T. Versoza",
    contactNumber: "+63 83 553 4300",
    contactEmail: "careers@holcim.com.ph",
    preparedByDesignation: "People Performance Lead",
    jobStatus: "active",
    postedAt: "2025-10-13T09:00:00+08:00",
    updatedAt: "2025-11-03T14:15:00+08:00",
  },
  {
    id: "gensan_job_025",
    employerId: "gensan_employer_25",
    positionTitle: "Depot Operations Lead",
    description: "Supervise loading racks, tank farm checks, and truck turnaround at Phoenix depot.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 38000,
    salaryMax: 46000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Fuel Depot Operations",
    education: "BS Mechanical Engineering",
    yearsExperience: 4,
    agePreference: "25-42",
    skills: ["Fuel Handling", "Safety Compliance", "Team Leadership"],
    requirements: ["Experience in fuel depot", "Knowledge of HSSE", "Can handle 24/7 operations"],
    vacantPositions: 1,
    location: "Tambler Industrial Complex, General Santos City",
    contactName: "Carlo Bryce Uy",
    contactNumber: "+63 83 552 7700",
    contactEmail: "terminal.hr@phoenixfuels.ph",
    preparedByDesignation: "Terminal HR Supervisor",
    jobStatus: "active",
    postedAt: "2025-10-12T09:10:00+08:00",
    updatedAt: "2025-11-02T13:30:00+08:00",
  },
  {
    id: "gensan_job_026",
    employerId: "gensan_employer_26",
    positionTitle: "Terminal Inventory Analyst",
    description: "Balance book vs physical stock, monitor pipeline receipts, and prepare DOE reports.",
    barangay: "Tambler",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 36000,
    salaryMax: 44000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Inventory Analytics",
    education: "BS Accountancy",
    yearsExperience: 3,
    agePreference: "24-38",
    skills: ["Advanced Excel", "Tank Gauging", "Regulatory Reporting"],
    requirements: ["Experience in oil & gas", "Understands terminal automation", "Can liaise with auditors"],
    vacantPositions: 1,
    location: "Makar Wharf Access Road, Tambler, General Santos City",
    contactName: "Engr. Lianne Rose Cueno",
    contactNumber: "+63 83 552 8800",
    contactEmail: "gensan.hr@shell.com",
    preparedByDesignation: "Terminal HSSE Manager",
    jobStatus: "active",
    postedAt: "2025-10-11T08:20:00+08:00",
    updatedAt: "2025-11-01T12:00:00+08:00",
  },
  {
    id: "gensan_job_027",
    employerId: "gensan_employer_27",
    positionTitle: "Enterprise Solutions Consultant",
    description: "Design integrated connectivity and Cloud solutions for SOCSKSARGEN accounts.",
    barangay: "Dadiangas South",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 45000,
    salaryMax: 60000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Enterprise Sales",
    education: "BS Electronics Engineering",
    yearsExperience: 5,
    agePreference: "26-45",
    skills: ["Solution Selling", "Cloud Services", "Stakeholder Engagement"],
    requirements: ["Handled enterprise telco accounts", "Strong presentation skills", "Willing to travel nearby provinces"],
    vacantPositions: 1,
    location: "Osmeña South St., Dadiangas South, General Santos City",
    contactName: "Michael Angelo Tabora",
    contactNumber: "+63 83 301 7600",
    contactEmail: "mindanao.hr@pldt.com.ph",
    preparedByDesignation: "Area HR Business Partner",
    jobStatus: "active",
    postedAt: "2025-10-10T09:10:00+08:00",
    updatedAt: "2025-10-31T11:50:00+08:00",
  },
  {
    id: "gensan_job_028",
    employerId: "gensan_employer_28",
    positionTitle: "Enterprise Account Manager",
    description: "Grow ICT revenues for Globe Business partners in South Cotabato and Sarangani.",
    barangay: "Dadiangas East",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 43000,
    salaryMax: 58000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Corporate Sales",
    education: "BS Marketing",
    yearsExperience: 4,
    agePreference: "25-42",
    skills: ["Account Planning", "Negotiation", "ICT Solutions"],
    requirements: ["Handled B2B accounts", "Can craft proposals", "Understands managed connectivity"],
    vacantPositions: 1,
    location: "J. Catolico Sr. Ave, Dadiangas East, General Santos City",
    contactName: "Jamie Rose Mangao",
    contactNumber: "+63 83 552 8808",
    contactEmail: "peoplexp@globe.com.ph",
    preparedByDesignation: "People Experience Lead",
    jobStatus: "active",
    postedAt: "2025-10-09T09:00:00+08:00",
    updatedAt: "2025-10-30T17:00:00+08:00",
  },
  {
    id: "gensan_job_029",
    employerId: "gensan_employer_29",
    positionTitle: "Workforce Analyst",
    description: "Forecast call volumes, build staffing plans, and publish interval-level schedules.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 32000,
    salaryMax: 42000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Workforce Management",
    education: "BS Mathematics",
    yearsExperience: 3,
    agePreference: "23-35",
    skills: ["WFM Tools", "Statistics", "MS Excel"],
    requirements: ["Experience with Aspect/Injixo", "Understands shrinkage planning", "Can run real-time reports"],
    vacantPositions: 3,
    location: "SPC Compound, National Highway, Lagao, General Santos City",
    contactName: "Bryan Carlo Catamco",
    contactNumber: "+63 83 305 6000",
    contactEmail: "gensan.recruitment@concentrix.com",
    preparedByDesignation: "Site Director",
    jobStatus: "active",
    postedAt: "2025-10-08T10:30:00+08:00",
    updatedAt: "2025-10-29T15:20:00+08:00",
  },
  {
    id: "gensan_job_030",
    employerId: "gensan_employer_30",
    positionTitle: "Training Delivery Lead",
    description: "Oversee nesting batches, calibrate trainers, and ensure CSAT readiness for new programs.",
    barangay: "Lagao",
    municipality: "General Santos City",
    province: "South Cotabato",
    salaryMin: 42000,
    salaryMax: 52000,
    salaryPeriod: "monthly",
    salaryType: "Monthly Gross",
    specialization: "Learning & Development",
    education: "Any 4-year course",
    yearsExperience: 5,
    agePreference: "25-42",
    skills: ["Facilitation", "Curriculum Design", "Coaching"],
    requirements: ["Handled BPO training", "Excellent communication", "Data-driven"],
    vacantPositions: 2,
    location: "SM City Gensan IT Tower, Lagao, General Santos City",
    contactName: "Katrina Mae Inigo",
    contactNumber: "+63 83 305 6200",
    contactEmail: "talent@sutherlandglobal.com",
    preparedByDesignation: "Talent Acquisition Senior Manager",
    jobStatus: "active",
    postedAt: "2025-10-07T09:15:00+08:00",
    updatedAt: "2025-10-28T13:45:00+08:00",
  },
];

function buildEmployerRows(passwordHash: string) {
  return employerSeeds.map((seed, index) => {
    const barangayMeta = barangayDirectory[seed.barangay];
    const idSuffix = (index + 1).toString().padStart(2, "0");
    const dateAccomplished = `2025-10-${String((index % 27) + 1).padStart(2, "0")}`;

    return {
      id: seed.id,
      establishmentName: seed.establishmentName,
      tradeName: seed.tradeName,
      houseStreetVillage: seed.street,
      barangay: seed.barangay,
      municipality: "General Santos City",
      province: "South Cotabato",
      completeAddress: `${seed.street}, ${seed.barangay}, General Santos City, South Cotabato 9500`,
      addressDetails: {
        street: seed.street,
        barangay: seed.barangay,
        city: "General Santos City",
        province: "South Cotabato",
        region: "SOCCSKSARGEN",
        zip: barangayMeta.zip,
        coordinates: { lat: seed.latitude, lng: seed.longitude },
        landmark: "Verified by PESO field visit",
      },
      contactNumber: seed.contactNumber,
      contactEmail: seed.contactEmail,
      contactPerson: {
        name: seed.contactPerson,
        designation: seed.contactDesignation,
        phone: seed.contactNumber,
        email: seed.contactEmail,
        officeHours: "08:00-17:00",
      },
      alternateContacts: [
        {
          name: "HR Shared Services",
          phone: "+63 83 888 7000",
          email: `support+${seed.id}@gensanworks.ph`,
          note: "Escalation desk",
        },
      ],
      email: seed.contactEmail,
      numberOfPaidEmployees: seed.employees,
      numberOfVacantPositions: seed.vacancies,
      industryCodes: [seed.industryCode],
      industryType: [seed.industryType],
      srsSubscriber: true,
      subscriptionStatus: "active",
      companyTin: `004-${idSuffix}56-789-000`,
      companyTaxIdNumber: `004-${idSuffix}56-789-000`,
      businessPermitNumber: `GENSAN-BP-2025-${idSuffix}`,
      bir2303Number: `BIR2303-${idSuffix}`,
      requirements: {
        documentChecklist: [
          { name: "SEC Registration", status: "valid" },
          { name: "Business Permit 2025", status: "valid" },
        ],
        companyType: seed.companyType,
        safetyOrientation: "2025-08-12",
        srsForm: "Form 2 rev2024",
        lastAuditFinding: "Compliant",
      },
      attachments: {
        businessPermitUrl: `https://gensanworks.local/permits/${seed.id}.pdf`,
        barangayClearanceUrl: `https://gensanworks.local/barangay/${seed.id}.pdf`,
        logoUrl: `https://gensanworks.local/logos/${seed.id}.png`,
      },
      chairpersonName: seed.chairpersonName,
      chairpersonContact: `+63 83 500 ${9000 + index}`,
      secretaryName: seed.secretaryName,
      secretaryContact: `+63 83 500 ${9300 + index}`,
      barangayChairperson: seed.barangayChairperson,
      barangaySecretary: seed.barangaySecretary,
      geographicIdentification: {
        region: "Region XII - SOCCSKSARGEN",
        province: "South Cotabato",
        city: "General Santos City",
        barangayCode: barangayMeta.code,
        psaUac: "126303000",
      },
      preparedByName: seed.contactPerson,
      preparedByDesignation: seed.contactDesignation,
      preparedByContact: seed.contactNumber,
      dateAccomplished,
      remarks: seed.remarks,
      isManpowerAgency: seed.isManpowerAgency ?? false,
      doleCertificationNumber: `DOLE-SOX-${String(500 + index).padStart(3, "0")}`,
      archived: false,
      archivedAt: null,
      passwordHash,
      hasAccount: true,
      createdAt: new Date(`2024-${String(((index % 12) + 1)).padStart(2, "0")}-15T08:00:00+08:00`),
      updatedAt: new Date(`2025-${String(((index % 12) + 1)).padStart(2, "0")}-30T10:00:00+08:00`),
    } satisfies typeof employersTable.$inferInsert;
  });
}

function buildJobRows() {
  const employerMap = new Map(employerSeeds.map((seed) => [seed.id, seed] as const));

  return jobSeeds.map((job, index) => {
    const employer = employerMap.get(job.employerId);
    if (!employer) {
      throw new Error(`Missing employer seed for job ${job.id}`);
    }
    const industryCode = employer.industryCode;
    const salaryAmount = Math.round((job.salaryMin + job.salaryMax) / 2);
    return {
      id: job.id,
      employerId: job.employerId,
      status: job.jobStatus,
      establishmentName: employer.establishmentName,
      positionTitle: job.positionTitle,
      description: job.description,
      location: job.location,
      salaryMin: job.salaryMin,
      salaryMax: job.salaryMax,
      salaryPeriod: job.salaryPeriod,
      salaryAmount,
      salaryType: job.salaryType,
      skills: job.skills.join(", "),
      industryCodes: [industryCode],
      minimumEducationRequired: job.education,
      mainSkillOrSpecialization: job.specialization,
      yearsOfExperienceRequired: job.yearsExperience,
      agePreference: job.agePreference,
      salary: {
        currency: "PHP",
        period: job.salaryPeriod,
        range: `${job.salaryMin.toLocaleString()}-${job.salaryMax.toLocaleString()}`,
      },
      startingSalaryOrWage: job.salaryMin,
      vacantPositions: job.vacantPositions,
      paidEmployees: job.paidEmployees ?? employer.employees,
      jobStatus: job.jobStatus,
      contact: {
        personName: job.contactName,
        phone: job.contactNumber,
        email: job.contactEmail,
      },
      requirements: job.requirements.map((req, reqIndex) => ({
        label: `Requirement ${reqIndex + 1}`,
        value: req,
      })),
      preparedByName: job.contactName,
      preparedByDesignation: job.preparedByDesignation,
      preparedByContact: job.contactNumber,
      dateAccomplished: job.postedAt,
      attachments: {
        jobDescriptionUrl: `https://gensanworks.local/jobs/${job.id}/jd.pdf`,
      },
      accountMetadata: {
        postedBy: "PESO General Santos",
        batch: "Dec-2025",
        reference: job.id,
      },
      barangay: job.barangay,
      municipality: job.municipality,
      province: job.province,
      archived: false,
      archivedAt: null,
      createdAt: new Date(job.postedAt),
      updatedAt: new Date(job.updatedAt),
    } satisfies typeof jobsTable.$inferInsert;
  });
}

async function main() {
  const db = await initializeDatabase();
  const passwordHash = await hashPassword(DEFAULT_PASSWORD);

  const employerRows = buildEmployerRows(passwordHash);
  const jobRows = buildJobRows();

  const employerIds = employerRows.map((row) => row.id);
  const jobIds = jobRows.map((row) => row.id);

  if (jobIds.length) {
    await db.delete(jobsTable).where(inArray(jobsTable.id, jobIds));
  }
  if (employerIds.length) {
    await db.delete(jobsTable).where(inArray(jobsTable.employerId, employerIds));
    await db.delete(employersTable).where(inArray(employersTable.id, employerIds));
  }

  if (employerRows.length) {
    await db.insert(employersTable).values(employerRows);
  }
  if (jobRows.length) {
    await db.insert(jobsTable).values(jobRows);
  }

  console.log(`\u2705 Inserted ${employerRows.length} General Santos employers and ${jobRows.length} jobs.`);
  console.log(`\u2139\ufe0f Default employer portal password set to ${DEFAULT_PASSWORD}`);
}

main().catch((error) => {
  console.error("\u274c Failed to seed General Santos employers/jobs", error);
  process.exit(1);
});
